### ISSUE TITLE
error

### ISSUE THREAD

**Issue by noobgramer** [karafra/ai-art#32]
![IMG_20221030_143915](https://user-images.githubusercontent.com/49397755/198871122-bd091b95-a091-4800-9f3b-462a16067084.jpg)
I can't figure this one out.

**Comment by noobgramer** [comment]
I'm hosting it on replit amd when I try to run it, it spits this out. What do I do?

**Comment by karafra** [comment]
its error inside your replit conf file, nothung i can do about that
